# Generated by Django 5.1.1 on 2024-09-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizstatus',
            name='current_quiz_data',
            field=models.JSONField(default=list),
        ),
    ]
